<?php
// $Id$

/**
 * @file
 * This module enables Google Fonts on your website.
 *
 * This module enables you to load fonts from the Google Fonts API
 * within your website. After selecting which fonts you want to use 
 * they will become available as working font-families in your CSS.
 */

/**
 * Implements hook_menu().
 */
function google_fonts_menu() {
  $items = array();

  $items['admin/config/system/google_fonts'] = array(
    'title' => 'Google Fonts',
    'description' => 'Select the Google Fonts you want to be available in your CSS.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('google_fonts_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'google_fonts.admin.inc',
  );
  
  $items['admin/config/system/google_fonts/select'] = array(
    'title' => 'Enable',
    'description' => 'Select the Google Fonts to use.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('google_fonts_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'google_fonts.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function google_fonts_init() {
  
  // We don't need to load the fonts twice as the admin interface
  // loads ALL fonts by default already
  if ($_GET['q'] == 'admin/settings/google_fonts') {
    return;
  }
  
  $fonts_to_load = array();
  $used_fonts = variable_get('google_fonts_enabled_fonts', array());
  foreach ($used_fonts as $font) {
    if (!empty($font)) {
      $fonts_to_load[] = _google_fonts_google_fontname($font);
    }
  }
  
  if (!empty($fonts_to_load)) {
    _google_fonts_load_css($fonts_to_load);
  }
}

/**
 * Add the CSS include to the HEAD of the page
 */
function _google_fonts_load_css($fonts_to_load) {
  
  drupal_add_css('http://fonts.googleapis.com/css?family=' . implode('|', $fonts_to_load), array('type' => 'external', 'weight' => CSS_SYSTEM));
}

/**
 * Return an array of available Google Fonts
 * TODO: When it becomes available, fetch the current fonts using 
 * an API call instead of hardcoding the font names
 */
function _google_fonts_available_fonts() {
  return array(
    'Cantarell',
    'Cardo',
    'Crimson Text',
    'Droid Sans',
    'Droid Sans Mono',
    'Droid Serif',
    'IM Fell DW Pica',
    'IM Fell DW Pica SC',
    'IM Fell Double Pica',
    'IM Fell Double Pica SC',
    'IM Fell English',
    'IM Fell English SC',
    'IM Fell French Canon SC',
    'IM Fell Great Primer',
    'IM Fell Great Primer SC',
    'Inconsolata',
    'Josefin Sans Std Light',
    'Lobster',
    'Molengo',
    'Nobile',
    'OFL Sorts Mill Goudy TT',
    'Old Standard TT',
    'Reenie Beanie',
    'Tangerine',
    'Vollkorn',
    'Yanone Kaffeesatz',
  );
}

/**
 * Format the font name as saved in the database (underscores instead of spaces)
 */
function _google_fonts_system_fontname($string) {
  return str_replace(' ', '_', $string);
}

/**
 * Format the font name as used in the Google CSS call (plus-signs instead of spaces)
 */
function _google_fonts_google_fontname($string) {
  return str_replace('_', '+', $string);
}