<?php
// $Id$

/**
 * @file
 * This module enables Google Fonts on your website.
 *
 * This module enables you to load fonts from the Google Fonts API
 * within your website. After selecting which fonts you want to use 
 * they will become available as working font-families in your CSS.
 */

/**
 * Implements hook_menu().
 */
function google_fonts_menu() {
  $items = array();

  $items['admin/config/system/google_fonts'] = array(
    'title' => 'Google Fonts',
    'description' => 'Select the Google Fonts you want to be available in your CSS.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('google_fonts_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'google_fonts.admin.inc',
  );
  
  $items['admin/config/system/google_fonts/select'] = array(
    'title' => 'Select fonts',
    'description' => 'Select the Google Fonts to use.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('google_fonts_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'google_fonts.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function google_fonts_init() {
  
  // We don't need to load the fonts twice as the admin interface
  // loads ALL fonts by default already
  if ($_GET['q'] == 'admin/config/system/google_fonts') {
    return;
  }
  
  $fonts_to_load = array();
  $used_fonts = variable_get('google_fonts_enabled_fonts', array());
  foreach ($used_fonts as $font) {
    if (!empty($font)) {
      $font_info = _google_fonts_get_font_info($font);
      $fonts_to_load[] = $font_info['path'];
    }
  }
  
  if (!empty($fonts_to_load)) {
    _google_fonts_load_css($fonts_to_load);
  }
}

/**
 * Add the CSS include to the HEAD of the page
 */
function _google_fonts_load_css($fonts_to_load) {
  $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 'https' : 'http';
  
  $chunks = array_chunk($fonts_to_load, 15);
  foreach ($chunks as $chunk) {
    drupal_add_css($protocol . '://fonts.googleapis.com/css?family=' . implode('|', $chunk), array('type' => 'external', 'weight' => CSS_SYSTEM));
  }
}

/**
 * Provides all needed details about Google fonts.
 * Thanks at @sreynen to provide this array in his @font-your-face module
 */
function _google_fonts_available_fonts() {

  $sil_license = array(
    'name' => 'SIL Open Font License, 1.1',
    'url' => 'http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL',
  );

  $apache_license = array(
    'name' => 'Apache License, version 2.0',
    'url' => 'http://www.apache.org/licenses/LICENSE-2.0.html',
  );

  return array(
    'Allan' => array(
      'path' => 'Allan',
      'fonts' => array(
        'Allan' => array(
          'family' => 'Allan',
          'path' => 'Allan:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Allerta' => array(
      'path' => 'Allerta',
      'fonts' => array(
        'Allerta' => array(
          'family' => 'Allerta',
          'path' => 'Allerta',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Allerta Stencil' => array(
      'path' => 'Allerta+Stencil',
      'fonts' => array(
        'Allerta Stencil' => array(
          'family' => 'Allerta Stencil',
          'path' => 'Allerta+Stencil',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Anonymous Pro' => array(
      'path' => 'Anonymous+Pro',
      'fonts' => array(
        'Anonymous Pro' => array(
          'family' => 'Anonymous Pro',
          'path' => 'Anonymous+Pro',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Anonymous Pro italic' => array(
          'family' => 'Anonymous Pro',
          'path' => 'Anonymous+Pro:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Anonymous Pro bold' => array(
          'family' => 'Anonymous Pro',
          'path' => 'Anonymous+Pro:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Anonymous Pro bold italic' => array(
          'family' => 'Anonymous Pro',
          'path' => 'Anonymous+Pro:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Arimo' => array(
      'path' => 'Arimo',
      'fonts' => array(
        'Arimo' => array(
          'family' => 'Arimo',
          'path' => 'Arimo',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Arimo italic' => array(
          'family' => 'Arimo',
          'path' => 'Arimo:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Arimo bold' => array(
          'family' => 'Arimo',
          'path' => 'Arimo:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Arimo bold italic' => array(
          'family' => 'Arimo',
          'path' => 'Arimo:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Arvo' => array(
      'path' => 'Arvo',
      'fonts' => array(
        'Arvo' => array(
          'family' => 'Arvo',
          'path' => 'Arvo',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Arvo italic' => array(
          'family' => 'Arvo',
          'path' => 'Arvo:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Arvo bold' => array(
          'family' => 'Arvo',
          'path' => 'Arvo:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Arvo bold italic' => array(
          'family' => 'Arvo',
          'path' => 'Arvo:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Bentham' => array(
      'path' => 'Bentham',
      'fonts' => array(
        'Bentham' => array(
          'family' => 'Bentham',
          'path' => 'Bentham',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Cantarell' => array(
      'path' => 'Cantarell',
      'fonts' => array(
        'Cantarell' => array(
          'family' => 'Cantarell',
          'path' => 'Cantarell',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Cantarell italic' => array(
          'family' => 'Cantarell',
          'path' => 'Cantarell:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Cantarell bold' => array(
          'family' => 'Cantarell',
          'path' => 'Cantarell:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Cantarell bold italic' => array(
          'family' => 'Cantarell',
          'path' => 'Cantarell:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Cardo' => array(
      'path' => 'Cardo',
      'fonts' => array(
        'Cardo' => array(
          'family' => 'Cardo',
          'path' => 'Cardo',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Coda' => array(
      'path' => 'Coda',
      'fonts' => array(
        'Coda' => array(
          'family' => 'Coda',
          'path' => 'Coda:800',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Cousine' => array(
      'path' => 'Cousine',
      'fonts' => array(
        'Cousine' => array(
          'family' => 'Cousine',
          'path' => 'Cousine',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Cousine italic' => array(
          'family' => 'Cousine',
          'path' => 'Cousine:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Cousine bold' => array(
          'family' => 'Cousine',
          'path' => 'Cousine:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Cousine bold italic' => array(
          'family' => 'Cousine',
          'path' => 'Cousine:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Covered By Your Grace' => array(
      'path' => 'Covered+By+Your+Grace',
      'fonts' => array(
        'Covered By Your Grace' => array(
          'family' => 'Covered By Your Grace',
          'path' => 'Covered+By+Your+Grace',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Crimson Text' => array(
      'path' => 'Crimson+Text',
      'fonts' => array(
        'Crimson Text' => array(
          'family' => 'Crimson Text',
          'path' => 'Crimson+Text',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Cuprum' => array(
      'path' => 'Cuprum',
      'fonts' => array(
        'Cuprum' => array(
          'family' => 'Cuprum',
          'path' => 'Cuprum',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Droid Sans' => array(
      'path' => 'Droid+Sans',
      'fonts' => array(
        'Droid Sans' => array(
          'family' => 'Droid Sans',
          'path' => 'Droid+Sans',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $apache_license,
        ),
        'Droid Sans bold' => array(
          'family' => 'Droid Sans',
          'path' => 'Droid+Sans:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $apache_license,
        ),
      ),
    ),
    'Droid Sans Mono' => array(
      'path' => 'Droid+Sans+Mono',
      'fonts' => array(
        'Droid Sans Mono' => array(
          'family' => 'Droid Sans Mono',
          'path' => 'Droid+Sans+Mono',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $apache_license,
        ),
      ),
    ),
    'Droid Serif' => array(
      'path' => 'Droid+Serif',
      'fonts' => array(
        'Droid Serif' => array(
          'family' => 'Droid Serif',
          'path' => 'Droid+Serif',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $apache_license,
        ),
        'Droid Serif italic' => array(
          'family' => 'Droid Serif',
          'path' => 'Droid+Serif:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $apache_license,
        ),
        'Droid Serif bold' => array(
          'family' => 'Droid Serif',
          'path' => 'Droid+Serif:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $apache_license,
        ),
        'Droid Serif bold italic' => array(
          'family' => 'Droid Serif',
          'path' => 'Droid+Serif:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $apache_license,
        ),
      ),
    ),
    'Geo' => array(
      'path' => 'Geo',
      'fonts' => array(
        'Geo' => array(
          'family' => 'Geo',
          'path' => 'Geo',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'IM Fell' => array(
      'path' => 'IM+Fell',
      'fonts' => array(
        'IM Fell DW Pica' => array(
          'family' => 'IM Fell DW Pica',
          'path' => 'IM+Fell+DW+Pica',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell DW Pica italic' => array(
          'family' => 'IM Fell DW Pica',
          'path' => 'IM+Fell+DW+Pica',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell DW Pica SC' => array(
          'family' => 'IM Fell DW Pica SC',
          'path' => 'IM+Fell+DW+Pica+SC',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell Double Pica' => array(
          'family' => 'IM Fell Double Pica',
          'path' => 'IM+Fell+Double+Pica',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell Double Pica italic' => array(
          'family' => 'IM Fell Double Pica',
          'path' => 'IM+Fell+Double+Pica:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell Double Pica SC' => array(
          'family' => 'IM Fell Double Pica SC',
          'path' => 'IM+Fell+Double+Pica+SC',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell English' => array(
          'family' => 'IM Fell English',
          'path' => 'IM+Fell+English',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell English italic' => array(
          'family' => 'IM Fell English',
          'path' => 'IM+Fell+English:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell English SC' => array(
          'family' => 'IM Fell English SC',
          'path' => 'IM+Fell+English+SC',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell French Canon' => array(
          'family' => 'IM Fell French Canon',
          'path' => 'IM+Fell+French+Canon',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell French Canon italic' => array(
          'family' => 'IM Fell French Canon',
          'path' => 'IM+Fell+French+Canon:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell French Canon SC' => array(
          'family' => 'IM Fell French Canon SC',
          'path' => 'IM+Fell+French+Canon+SC',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell Great Primer' => array(
          'family' => 'IM Fell Great Primer',
          'path' => 'IM+Fell+Great+Primer',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell Great Primer italic' => array(
          'family' => 'IM Fell Great Primer',
          'path' => 'IM+Fell+Great+Primer:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'IM Fell Great Primer SC' => array(
          'family' => 'IM Fell Great Primer SC',
          'path' => 'IM+Fell+Great+Primer+SC',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Inconsolata' => array(
      'path' => 'Inconsolata',
      'fonts' => array(
        'Inconsolata' => array(
          'family' => 'Inconsolata',
          'path' => 'Inconsolata',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Josefin Sans' => array(
      'path' => 'Josefin+Sans',
      'fonts' => array(
        'Josefin Sans 100' => array(
          'family' => 'Josefin Sans',
          'path' => 'Josefin+Sans:100',
          'style' => 'normal',
          'weight' => '100',
          'license' => $sil_license,
        ),
        'Josefin Sans 100 italic' => array(
          'family' => 'Josefin Sans',
          'path' => 'Josefin+Sans:100italic',
          'style' => 'italic',
          'weight' => '100',
          'license' => $sil_license,
        ),
        'Josefin Sans 300' => array(
          'family' => 'Josefin Sans',
          'path' => 'Josefin+Sans:light',
          'style' => 'normal',
          'weight' => 'light',
          'license' => $sil_license,
        ),
        'Josefin Sans 300 italic' => array(
          'family' => 'Josefin Sans',
          'path' => 'Josefin+Sans:lightitalic',
          'style' => 'italic',
          'weight' => 'light',
          'license' => $sil_license,
        ),
        'Josefin Sans 400' => array(
          'family' => 'Josefin Sans',
          'path' => 'Josefin+Sans:regular',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Josefin Sans 400 italic' => array(
          'family' => 'Josefin Sans',
          'path' => 'Josefin+Sans:regularitalic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Josefin Sans 600' => array(
          'family' => 'Josefin Sans',
          'path' => 'Josefin+Sans:600',
          'style' => 'normal',
          'weight' => '600',
          'license' => $sil_license,
        ),
        'Josefin Sans 600 italic' => array(
          'family' => 'Josefin Sans',
          'path' => 'Josefin+Sans:600italic',
          'style' => 'italic',
          'weight' => '600',
          'license' => $sil_license,
        ),
        'Josefin Sans 700' => array(
          'family' => 'Josefin Sans',
          'path' => 'Josefin+Sans:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Josefin Sans 700 italic' => array(
          'family' => 'Josefin Sans',
          'path' => 'Josefin+Sans:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Josefin Slab' => array(
      'path' => 'Josefin+Slab',
      'fonts' => array(
        'Josefin Slab 100' => array(
          'family' => 'Josefin Slab',
          'path' => 'Josefin+Slab:100',
          'style' => 'normal',
          'weight' => '100',
          'license' => $sil_license,
        ),
        'Josefin Slab 100 italic' => array(
          'family' => 'Josefin Slab',
          'path' => 'Josefin+Slab:100italic',
          'style' => 'italic',
          'weight' => '100',
          'license' => $sil_license,
        ),
        'Josefin Slab 300' => array(
          'family' => 'Josefin Slab',
          'path' => 'Josefin+Slab:light',
          'style' => 'normal',
          'weight' => 'light',
          'license' => $sil_license,
        ),
        'Josefin Slab 300 italic' => array(
          'family' => 'Josefin Slab',
          'path' => 'Josefin+Slab:lightitalic',
          'style' => 'italic',
          'weight' => 'light',
          'license' => $sil_license,
        ),
        'Josefin Slab 400' => array(
          'family' => 'Josefin Slab',
          'path' => 'Josefin+Slab:regular',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Josefin Slab 400 italic' => array(
          'family' => 'Josefin Slab',
          'path' => 'Josefin+Slab:regularitalic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Josefin Slab 600' => array(
          'family' => 'Josefin Slab',
          'path' => 'Josefin+Slab:600',
          'style' => 'normal',
          'weight' => '600',
          'license' => $sil_license,
        ),
        'Josefin Slab 600 italic' => array(
          'family' => 'Josefin Slab',
          'path' => 'Josefin+Slab:600italic',
          'style' => 'italic',
          'weight' => '600',
          'license' => $sil_license,
        ),
        'Josefin Slab 700' => array(
          'family' => 'Josefin Slab',
          'path' => 'Josefin+Slab:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Josefin Slab 700 italic' => array(
          'family' => 'Josefin Slab',
          'path' => 'Josefin+Slab:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Just Me Again Down Here' => array(
      'path' => 'Just+Me+Again+Down+Here',
      'fonts' => array(
        'Just Me Again Down Here' => array(
          'family' => 'Just Me Again Down Here',
          'path' => 'Just+Me+Again+Down+Here',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Kenia' => array(
      'path' => 'Kenia',
      'fonts' => array(
        'Kenia' => array(
          'family' => 'Kenia',
          'path' => 'Kenia',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Lato' => array(
      'path' => 'Lato',
      'fonts' => array(
        'Lato 100' => array(
          'family' => 'Lato',
          'path' => 'Lato:100',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Lato 100 italic' => array(
          'family' => 'Lato',
          'path' => 'Lato:100italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Lato light' => array(
          'family' => 'Lato',
          'path' => 'Lato:light',
          'style' => 'normal',
          'weight' => 'light',
          'license' => $sil_license,
        ),
        'Lato light italic' => array(
          'family' => 'Lato',
          'path' => 'Lato:lightlitalic',
          'style' => 'italic',
          'weight' => 'light',
          'license' => $sil_license,
        ),
        'Lato regular' => array(
          'family' => 'Lato',
          'path' => 'Lato:regular',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Lato regular italic' => array(
          'family' => 'Lato',
          'path' => 'Lato:regularlitalic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Lato bold' => array(
          'family' => 'Lato',
          'path' => 'Lato:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Lato bold italic' => array(
          'family' => 'Lato',
          'path' => 'Lato:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Lato 900' => array(
          'family' => 'Lato',
          'path' => 'Lato:900',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Lato 900 italic' => array(
          'family' => 'Lato',
          'path' => 'Lato:900italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Lobster' => array(
      'path' => 'Lobster',
      'fonts' => array(
        'Lobster' => array(
          'family' => 'Lobster',
          'path' => 'Lobster',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Molengo' => array(
      'path' => 'Molengo',
      'fonts' => array(
        'Molengo' => array(
          'family' => 'Molengo',
          'path' => 'Molengo',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Mountains of Christmas' => array(
      'path' => 'Mountains+of+Christmas',
      'fonts' => array(
        'Mountains of Christmas' => array(
          'family' => 'Mountains of Christmas',
          'path' => 'Mountains+of+Christmas',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $apache_license,
        ),
      ),
    ),
    'Neucha' => array(
      'path' => 'Neucha',
      'fonts' => array(
        'Neucha' => array(
          'family' => 'Neucha',
          'path' => 'Neucha',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Neuton' => array(
      'path' => 'Neuton',
      'fonts' => array(
        'Neuton' => array(
          'family' => 'Neuton',
          'path' => 'Neuton',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $apache_license,
        ),
      ),
    ),
    'Nobile' => array(
      'path' => 'Nobile',
      'fonts' => array(
        'Nobile' => array(
          'family' => 'Nobile',
          'path' => 'Nobile',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Nobile italic' => array(
          'family' => 'Nobile',
          'path' => 'Nobile:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Nobile bold' => array(
          'family' => 'Nobile',
          'path' => 'Nobile:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Nobile bold italic' => array(
          'family' => 'Nobile',
          'path' => 'Nobile:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'OFL Sorts Mill Goudy TT' => array(
      'path' => 'OFL+Sorts+Mill+Goudy+TT',
      'fonts' => array(
        'OFL Sorts Mill Goudy TT' => array(
          'family' => 'OFL Sorts Mill Goudy TT',
          'path' => 'OFL+Sorts+Mill+Goudy+TT',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'OFL Sorts Mill Goudy TT italic' => array(
          'family' => 'OFL Sorts Mill Goudy TT',
          'path' => 'OFL+Sorts+Mill+Goudy+TT:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Old Standard TT' => array(
      'path' => 'Old+Standard+TT',
      'fonts' => array(
        'Old Standard TT' => array(
          'family' => 'Old Standard TT',
          'path' => 'Old+Standard+TT',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Old Standard TT italic' => array(
          'family' => 'Old Standard TT',
          'path' => 'Old+Standard+TT:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Old Standard TT bold' => array(
          'family' => 'Old Standard TT',
          'path' => 'Old+Standard+TT:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Orbitron' => array(
      'path' => 'Orbitron',
      'fonts' => array(
        'Orbitron' => array(
          'family' => 'Orbitron',
          'path' => 'Orbitron',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Orbitron 500' => array(
          'family' => 'Orbitron',
          'path' => 'Orbitron:500',
          'style' => 'normal',
          'weight' => '500',
          'license' => $sil_license,
        ),
        'Orbitron bold' => array(
          'family' => 'Orbitron',
          'path' => 'Orbitron:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Orbitron 900' => array(
          'family' => 'Orbitron',
          'path' => 'Orbitron:900',
          'style' => 'normal',
          'weight' => '900',
          'license' => $sil_license,
        ),
      ),
    ),
    'PT Sans' => array(
      'path' => 'PT+Sans',
      'fonts' => array(
        'PT Sans' => array(
          'family' => 'PT Sans',
          'path' => 'PT+Sans',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'PT Sans italic' => array(
          'family' => 'PT Sans',
          'path' => 'PT+Sans:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'PT Sans bold' => array(
          'family' => 'PT Sans',
          'path' => 'PT+Sans:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'PT Sans bold italic' => array(
          'family' => 'PT Sans',
          'path' => 'PT+Sans:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'PT Sans Caption' => array(
          'family' => 'PT Sans Caption',
          'path' => 'PT+Sans+Caption',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'PT Sans Caption bold' => array(
          'family' => 'PT Sans Caption',
          'path' => 'PT+Sans+Caption:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'PT Sans Narrow' => array(
          'family' => 'PT Sans Narrow',
          'path' => 'PT+Sans+Narrow',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'PT Sans Narrow bold' => array(
          'family' => 'PT Sans Narrow',
          'path' => 'PT+Sans+Narrow:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Philosopher' => array(
      'path' => 'Philosopher',
      'fonts' => array(
        'Philosopher' => array(
          'family' => 'Philosopher',
          'path' => 'Philosopher',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Puritan' => array(
      'path' => 'Puritan',
      'fonts' => array(
        'Puritan' => array(
          'family' => 'Puritan',
          'path' => 'Puritan',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Puritan italic' => array(
          'family' => 'Puritan',
          'path' => 'Puritan:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Puritan bold' => array(
          'family' => 'Puritan',
          'path' => 'Puritan:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Puritan bold italic' => array(
          'family' => 'Puritan',
          'path' => 'Puritan:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Raleway' => array(
      'path' => 'Raleway',
      'fonts' => array(
        'Raleway' => array(
          'family' => 'Raleway',
          'path' => 'Raleway:100',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Reenie Beanie' => array(
      'path' => 'Reenie+Beanie',
      'fonts' => array(
        'Reenie Beanie' => array(
          'family' => 'Reenie Beanie',
          'path' => 'Reenie+Beanie',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Sniglet' => array(
      'path' => 'Sniglet',
      'fonts' => array(
        'Sniglet' => array(
          'family' => 'Sniglet',
          'path' => 'Sniglet:800',
          'style' => 'normal',
          'weight' => '800',
          'license' => $sil_license,
        ),
      ),
    ),
    'Syncopate' => array(
      'path' => 'Syncopate',
      'fonts' => array(
        'Syncopate' => array(
          'family' => 'Syncopate',
          'path' => 'Syncopate',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $apache_license,
        ),
      ),
    ),
    'Tangerine' => array(
      'path' => 'Tangerine',
      'fonts' => array(
        'Tangerine' => array(
          'family' => 'Tangerine',
          'path' => 'Tangerine',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Tangerine bold' => array(
          'family' => 'Tangerine',
          'path' => 'Tangerine:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Tinos' => array(
      'path' => 'Tinos',
      'fonts' => array(
        'Tinos' => array(
          'family' => 'Tinos',
          'path' => 'Tinos',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Tinos italic' => array(
          'family' => 'Tinos',
          'path' => 'Tinos:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Tinos bold' => array(
          'family' => 'Tinos',
          'path' => 'Tinos:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Tinos bold italic' => array(
          'family' => 'Tinos',
          'path' => 'Tinos:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'UnifrakturCook' => array(
      'path' => 'UnifrakturCook',
      'fonts' => array(
        'UnifrakturCook' => array(
          'family' => 'UnifrakturCook',
          'path' => 'UnifrakturCook:bold',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'UnifrakturMaguntia' => array(
      'path' => 'UnifrakturMaguntia',
      'fonts' => array(
        'UnifrakturMaguntia' => array(
          'family' => 'UnifrakturMaguntia',
          'path' => 'UnifrakturMaguntia',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Vibur' => array(
      'path' => 'Vibur',
      'fonts' => array(
        'Vibur' => array(
          'family' => 'Vibur',
          'path' => 'Vibur',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
      ),
    ),
    'Vollkorn' => array(
      'path' => 'Vollkorn',
      'fonts' => array(
        'Vollkorn' => array(
          'family' => 'Vollkorn',
          'path' => 'Vollkorn',
          'style' => 'normal',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Vollkorn italic' => array(
          'family' => 'Vollkorn',
          'path' => 'Vollkorn:italic',
          'style' => 'italic',
          'weight' => 'normal',
          'license' => $sil_license,
        ),
        'Vollkorn bold' => array(
          'family' => 'Vollkorn',
          'path' => 'Vollkorn:bold',
          'style' => 'normal',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
        'Vollkorn bold italic' => array(
          'family' => 'Vollkorn',
          'path' => 'Vollkorn:bolditalic',
          'style' => 'italic',
          'weight' => 'bold',
          'license' => $sil_license,
        ),
      ),
    ),
    'Yanone Kaffeesatz' => array(
      'path' => 'Yanone+Kaffeesatz',
      'fonts' => array(
        'Yanone Kaffeesatz 200' => array(
          'family' => 'Yanone Kaffeesatz',
          'path' => 'Yanone+Kaffeesatz:200',
          'style' => 'normal',
          'weight' => '200',
          'license' => $sil_license,
        ),
        'Yanone Kaffeesatz 300' => array(
          'family' => 'Yanone Kaffeesatz',
          'path' => 'Yanone+Kaffeesatz:300',
          'style' => 'normal',
          'weight' => '300',
          'license' => $sil_license,
        ),
        'Yanone Kaffeesatz 400' => array(
          'family' => 'Yanone Kaffeesatz',
          'path' => 'Yanone+Kaffeesatz:400',
          'style' => 'normal',
          'weight' => '400',
          'license' => $sil_license,
        ),
        'Yanone Kaffeesatz 700' => array(
          'family' => 'Yanone Kaffeesatz',
          'path' => 'Yanone+Kaffeesatz:700',
          'style' => 'normal',
          'weight' => '700',
          'license' => $sil_license,
        ),
      ),
    ),
  );
} // google_fonts_api_list

/**
 * Format the font name as saved in the database (underscores instead of spaces)
 */
function _google_fonts_system_fontname($string) {
  return str_replace(' ', '_', $string);
}

/**
 * Format the font name as class_name (underscores instead of : and +)
 */
function _google_fonts_path_to_classname($string) {
  return strtolower(str_replace('+', '_', str_replace(':', '_', $string)));
}

/**
 * Return the path of this font
 * If it is a child font of a larger family, scan the array to determine its path
 */
function _google_fonts_get_font_info($font, $full_font = '') {
  $available_fonts = _google_fonts_available_fonts();
    
  if (empty($full_font)) {
    $full_font = $font;
  }
  if (isset($available_fonts[$font]['fonts'])) {
    if (isset($available_fonts[$font]['fonts'][$full_font])) {
      return $available_fonts[$font]['fonts'][$full_font];
    }
    else {
      return $available_fonts[$font];
    }
  }
  else{
    // Try the string without the last word to determine the parent
    $font = substr($font, 0, strrpos($font, " "));
    return _google_fonts_get_font_info($font, $full_font);
  }
}