<?php

/**
 * @file
 * Installation file for Google Fonts module.
 */

function google_fonts_install() {
  drupal_set_message(st('To use the Google Fonts on your website, your have to <a href="!settings_link">select which ones to use</a>.', array('!settings_link' => url('admin/config/system/google_fonts'))));
}

/**
 * Implements hook_update_last_removed().
 */
function google_fonts_update_last_removed() {
  return 7100;
}
